#!/bin/bash

die ()
{
set +xe
>&2 echo ""
>&2 echo "================================ DIE ==============================="

>&2 echo "$@"

>&2 echo "Call stack:"
local n=$((${#BASH_LINENO[@]}-1))
local i=0
while [ $i -lt $n ]; do
local line=${BASH_LINENO[i]}
local func=${FUNCNAME[i+1]}

i=$((i+1))

>&2 echo "    [$i] -- line $line -- $func"
done
>&2  echo "================================ END ==============================="
exit 1
}

[[ $# -ne 1 ]] && die "Usage: gentoo-chroot DIR"


mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --bind /run /mnt/gentoo/run

mount --make-rslave /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/dev
mount --make-slave /mnt/gentoo/run


chroot $1 /bin/bash
source /etc/profile
export PS1="(chroot) ${PS1}"
