#!/bin/bash

pushd "$(git rev-parse --show-toplevel)"

# check whether x86-64-v3 is supported: https://www.gentoo.org/news/2024/02/04/x86-64-v3.html
mkdir -p portage/binrepos.conf
arch='x86-64'
if ld.so --help | grep 'x86-64-v3' | grep -q supported; then
    arch='x86-64-v3'
fi

hosts=(mirrors.tuna.tsinghua.edu.cn mirrors.neusoft.edu.cn mirrors.163.com )

idx=0
echo > portage/binrepos.conf/gentoobinhost.conf
for host in "${hosts[@]}"; do
    cat <<- EOF >> portage/binrepos.conf/gentoobinhost.conf
[binhost$idx]
priority = $((9999-idx))
sync-uri = https://${host}/gentoo/releases/amd64/binpackages/23.0/${arch}/

EOF
    idx=$((idx+1))
done

# generate CPU_FLAGS_X86
if command -v cpuid2cpuflags > /dev/null; then
    echo "*/* $(cpuid2cpuflags)" > portage/package.use/00cpu-flags
fi

popd
exit 0
