#!/bin/bash

echo "PWD: ${PWD}"

pushd "$(git rev-parse --show-toplevel)"

# check whether x86-64-v3 is supported: https://www.gentoo.org/news/2024/02/04/x86-64-v3.html
mkdir -p portage/binrepos.conf
arch='x86-64'
if ld.so --help | grep 'x86-64-v3' | grep -q supported; then
    arch='x86-64-v3'
fi

cat <<- EOF > portage/binrepos.conf/gentoobinhost.conf
[binhost]
priority = 9999
sync-uri = https://mirrors.tuna.tsinghua.edu.cn/gentoo/releases/amd64/binpackages/23.0/${arch}/
EOF

# generate CPU_FLAGS_X86
if command -v cpuid2cpuflags > /dev/null; then
    echo "*/* $(cpuid2cpuflags)" > portage/package.use/00cpu-flags
fi

sudo rsync --exclude=.cache/ --exclude=cmake_build_* -Pa portage/ /etc/portage/
popd

exit 0
